### ISSUE TITLE
Certificate Issue sni-support-required-for-valid-ssl

### ISSUE THREAD

**Issue by krismeister** [Valian/docker-nginx-auto-ssl#4]
Hi, thanks for your work on this docker image.

I can't get secure certificates to be issued.
Chrome indicates the certificate is a self-signed non-3rd-party issued certificate

![certificate-issue](https://user-images.githubusercontent.com/1367719/42131767-e9c3a0f0-7cd7-11e8-9951-0c6e774300e3.png)

From my docker-compose

    version: "3"

    services:
      nginx_ssl:
        image: valian/docker-nginx-auto-ssl
        restart: on-failure
        ports:
          - "443:443"
          - "80:80"
        environment:
          - ALLOWED_DOMAINS=site1.com,site2.com
          - SITES=site1.com=other_nginx:8181;site2.com=other_nginx:8080
          - FORCE_HTTPS=true
        links:
          - "other_nginx:other_nginx"

Am I using docker-nginx-auto-ssl correctly?

**Comment by Valian** [comment]
Hi @krismeister!

In a case when certificate can't be generated correctly, OpenResty is using a self-signed cert as a fallback (the one you see in your example). From your configuration I see you are using default values, they won't work properly. Remember, you can issue a valid Let's Encrypt certificate only for a domain. You can't test it on your local machine, because DNS entry for your domain probably won't point to your home IP address. So, assuming you want to host your website on `https://example.com`, you have a server with IP address `123.123.123.123`, and your domain DNS is configured properly:

```bash
> nslookup example.com  # use your domain, not example.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	example.com
Address: 123.123.123.123  # here should be your server address
```

Then, deploying that docker-compose.yml on a server and accessing `https://example.com` will generate a certificate for you:

```
version: "3"

services:
  nginx_ssl:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - "443:443"
      - "80:80"
    volumes:
      # we want to persist issued certificates in a volume
      - ssl-data:/etc/resty-auto-ssl
    environment:
      - ALLOWED_DOMAINS=example.com
      - FORCE_HTTPS=true

volumes:
  ssl-data:
``` 

Remember that you'll see just a default OpenResty page in that case. You have to proxy requests to your own application.

Hope it will solve your issue!
