### ISSUE TITLE
how to use FastCGI 

### ISSUE THREAD

**Issue by ssatz** [Valian/docker-nginx-auto-ssl#42]
Hi, 

Thanks for the wonderful docker image.
How to use it for FastCGI  for php app(laravel in my case).
I tried to overwrite the server-proxy.conf with FastCGI, but it does show only default openresty page. 

```
version: '3.7'
services:
  app:
    build: ./docker/php/prod
    depends_on:
      - mongodb
      - cache
      - queue
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    env_file:
      - .env

  web:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./:/var/www/
    environment:
      FORCE_HTTPS: true
      ALLOWED_DOMAINS: '(www|admin).parttimeworks.in'
      SITES: 'www.parttimeworks.in=app:9000,admin.parttimeworks.in=app:9000'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    env_file:6
      - .env

  mariadb-master:
    image: 'bitnami/mariadb:10.2.17-debian-9-r36'
    container_name: mariadb-master
    volumes:
      - 'db-master-data:/bitnami/mariadb'
    ports:
      - 32797:3306
    environment:
      - MARIADB_REPLICATION_MODE=master
      - "MARIADB_REPLICATION_USER=${REPLICATION_USER}"
      - "MARIADB_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}"
      - "MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}"
      - "MARIADB_USER=${DB_USERNAME}"
      - "MARIADB_PASSWORD=${DB_PASSWORD}"
      - "MARIADB_DATABASE=${DB_DATABASE}"
    env_file:
      - .env

  mariadb-slave:
    image: 'bitnami/mariadb:10.2.17-debian-9-r36'
    container_name: mariadb-slave
    ports:
      - 32796:3306
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - "MARIADB_REPLICATION_USER=${REPLICATION_USER}"
      - "MARIADB_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}"
      - MARIADB_MASTER_HOST=mariadb-master
      - "MARIADB_MASTER_ROOT_PASSWORD=${ROOT_PASSWORD}"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: dailyonline_mongodb
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DATABASE}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
    volumes:
      - mongodb:/data/db
    ports:
      - 27017
    command: mongod --auth --storageEngine wiredTiger

    #laravel cron
  cron:
    build: ./docker/crontab
    #container_name: cron
    volumes:
      - ./:/var/www/
    depends_on:
      - app
    env_file:
      - .env

  #laravel worker
  worker:
    build: ./docker/worker
    #container_name: worker
    volumes:
      - ./:/var/www/
    depends_on:
      - queue
      - cache
      - mongodb
    env_file:
      - .env

  cache:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 9081:6379
    env_file:
      - .env

  echo:
    build: ./docker/echo-server
    ports:
      - '6001:6001'
    depends_on:
      - app
      - web
    links:
      - web
      - cache
    volumes:
      - ./docker/echo-server/prod/laravel-echo-server.json:/app/laravel-echo-server.json:ro
      - ./storage/certs:/app/storage/certs:ro


  queue:
    image: schickling/beanstalkd


  nodejs:
    build: ./docker/nodejs
    volumes:
      - ./:/var/www/

volumes:
  db-master-data:
    driver: local
  mongodb:
  ssl_data:

networks:
  default:
    external:
      name: nginx-proxy
```

Best Regards,
sathish

**Comment by Valian** [comment]
Hi @ssatz 

If your `app` container is a standalone server already serving php pages on port 9000, then FastCGI is not needed, for nginx-auto-ssl your app will be just a normal HTTP server. If you're seeing a default Nginx page, it might mean that NGINX is not correctly routing you. 

How are you accessing your application? You have to use one of the domains defined in `SITES` variable, otherwise NGINX [won't use the correct server for you](http://nginx.org/en/docs/http/request_processing.html). So using eg. `localhost` won't work since HOST header won't match any domains defined by you. You have to access `www.parttimeworks.in` to make it work (it's reasonable - certificate can't be generated if the domain is not pointing directly to your nginx instance). 

Also, you can just `exec` inside running image and see generated files. Something like `docker-compose exec --workdir /etc/nginx/conf.d web bash -c "cat *"` should do. 

If it's still not enough, tell me how exactly you're accessing your application and show me the logs from container.

**Comment by ssatz** [comment]
Hi @Valian ,

Thanks for the reply!
I am able to solve it .

Below is my docker file
```
FROM valian/docker-nginx-auto-ssl
COPY server-proxy.conf /usr/local/openresty/nginx/conf/server-proxy.conf
```
below is my server-proxy.conf
```
server {
  listen 443 ssl http2;
     listen [::]:443 ssl http2;
     server_name parttimeworks.in;
    # index index.php index.html;
    # root /var/www/public;

      include resty-server-https.conf;
     
       return 301 https://www.parttimeworks.in$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name  www.parttimeworks.in;
    index index.php index.html;
    root /var/www/public;

      include resty-server-https.conf;

      location / {
                  try_files $uri /index.php?$args;
              }

      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass app:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
          add_header X-XSS-Protection "1; mode=block" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-Frame-Options "DENY" always;
          #CSP
         # add_header Content-Security-Policy "frame-src 'self'; default-src 'self'; script-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://ajax.googleapis.com; img-src 'self'; style-src 'self' https://maxcdn.bootstrapcdn.com; font-src 'self' data: https://maxcdn.bootstrapcdn.com; form-action 'self'; upgrade-insecure-requests;" always;
          add_header Referrer-Policy "strict-origin-when-cross-origin" always;
      }

      location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|svg|woff|woff2|ttf)\$ {
                   expires 1M;
                   access_log off;
                   add_header Cache-Control "public";
                 }

                 location ~* \.(?:css|js)\$ {
                   expires 7d;
                   access_log off;
                   add_header Cache-Control "public";
                 }

                 location ~ /\.ht {
                     deny  all;
                 }

               # Enable Gzip compressed.
               gzip on;
               gzip_static on;
               # Enable compression both for HTTP/1.0 and HTTP/1.1.
               gzip_http_version  1.1;

               # Compression level (1-9).
               # 5 is a perfect compromise between size and cpu usage, offering about
               # 75% reduction for most ascii files (almost identical to level 9).
               gzip_comp_level    5;

               # Don't compress anything that's already small and unlikely to shrink much
               # if at all (the default is 20 bytes, which is bad as that usually leads to
               # larger files after gzipping).
               gzip_min_length    256;

               # Compress data even for clients that are connecting to us via proxies,
               # identified by the "Via" header (required for CloudFront).
               gzip_proxied       any;

               # Tell proxies to cache both the gzipped and regular version of a resource
               # whenever the client's Accept-Encoding capabilities header varies;
               # Avoids the issue where a non-gzip capable client (which is extremely rare
               # today) would display gibberish if their proxy gave them the gzipped version.
               gzip_vary          on;

               # Compress all output labeled with one of the following MIME-types.
               gzip_types
                 application/atom+xml
                 application/javascript
                 application/json
                 application/rss+xml
                 application/vnd.ms-fontobject
                 application/x-font-ttf
                 application/x-web-app-manifest+json
                 application/xhtml+xml
                 application/xml
                 font/opentype
                 image/svg+xml
                 image/x-icon
                 text/css
                 text/plain
                 text/x-component;
               # text/html is always compressed by HttpGzipModule

}
```
I need to locate the .cert and .key file for Websocket SSL.  Unfortunately am not able to find the file in /etc/resty-auto-ssl

```
  echo:
    build: ./docker/echo-server
    ports:
      - '6001:6001'
    depends_on:
      - app
      - web
    links:
      - web
      - cache
    volumes:
      - ./docker/echo-server/prod/laravel-echo-server.json:/app/laravel-echo-server.json:ro
      - ssl_data:/etc/resty-auto-ss
```
