### ISSUE TITLE
how to connect redis with docker-compose

### ISSUE THREAD

**Issue by karkovich** [Valian/docker-nginx-auto-ssl#48]
Hi, 
I want to up redis and docker-nginx-auto-ssl with docker-compose and connect them to work together. 
I tried to use this configuration:

```
version: '3'
services:
  redis:
    container_name: redis
    image: redis

  nginx:
    container_name: nginx
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    environment: 
        STORAGE_ADAPTER: redis
        REDIS_HOST: redis
        REDIS_PORT: 6379
```

however i'm not sure it's valid:

        REDIS_HOST: redis
        REDIS_PORT: 6379
