### ISSUE TITLE
How to config backend and frontend with same domain

### ISSUE THREAD

**Issue by bugb** [Valian/docker-nginx-auto-ssl#52]
This is an example from README:
```
version: '2'
services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'yourdomain.com'
      SITES: 'yourdomain.com=myapp:80'
  
  # your application, listening on port specified in `SITES` env variable
  myapp:
    image: nginx

volumes:
  ssl_data:

```
Here I can see `yourdomain.com=myapp:80` will map yourdomain to frontend container `my app` (port 80), now if I want to use `backend`  container with the same server, how can I make it works?

I have tried but it seems not work: 

```
version: '2'
services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'yourdomain.com'
      SITES: 'yourdomain.com=myapp:80; yourdomain.com:8080=mybackendapp:8080'
  
  # your application, listening on port specified in `SITES` env variable
  myapp:
    image: nginx

  mybackendapp:
     image: myimage


volumes:
  ssl_data:

```
