### ISSUE TITLE
403 Error with Custom Port

### ISSUE THREAD

**Issue by 0x3639** [Valian/docker-nginx-auto-ssl#59]
Thank you for this nice project.  I've setup a custom `.conf` file to forward port 35997 over SSL to a back end server

here is the `docker-compose.yml` file:

```
version: '2'

services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 35997:35997
      - 35998:35998
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./conf:/etc/nginx/conf.d
    environment:
      ALLOWED_DOMAINS: '00.deeznnutz.com'
      #SITES: 'yourdomain.com=myapp:80'
  
  znnd:
    build: .
    container_name: znnd
    ports:
      - "35995:35995"
    restart: always
    volumes:
      - data:/root/.znn

volumes:
  data:
  ssl_data:
```

and here is the `35997.conf` file under `./conf`

```
server {
  listen 35997 ssl default_server;
  
  include resty-server-https.conf;

  location / {
    proxy_pass http://znnd:35997;
  }
}
```

I'm getting a 403 error when I query the endpoint:  https://reqbin.com/sqq4defa 
Can you see what I'm doing wrong?  Thank you.

```
curl -X GET https://00.deeznnutz.com:35997 -H "content-type: application/json" -d '{"jsonrpc": "2.0", "id": 40, "method": "stats.networkInfo", "params": []}'
```
